*! hxrun 1.0.0  09aug2026
*! Execute native Stata commands generated by the unified empirical toolbox
program define hxrun, rclass
    version 16.0
    syntax , ACTION(string) [VARS(string asis) BY(name) IFCOND(string asis) ///
        OPTIONS(string asis) STATS(string asis) VALUE(string) ///
        NEWVAR(name) TARGET(name) ///
        USINGFILE(string) DIRECTION(string) STUBS(string asis) IDVAR(name) ///
        JVAR(name) Y(name) X(string asis) CONTROLS(string asis) ///
        ABSORB(string asis) CLUSTER(name) ENDO(string asis) ///
        INST(string asis) VARIANT(string) SE(string) EXPR(string asis)]

    local action = lower(trim(`"`action'"'))
    local vars = trim(`"`vars'"')
    local ifcond = trim(`"`ifcond'"')
    local options = trim(`"`options'"')
    local stats = trim(`"`stats'"')
    local usingfile = trim(`"`usingfile'"')
    local direction = lower(trim(`"`direction'"'))
    local stubs = trim(`"`stubs'"')
    local x = trim(`"`x'"')
    local controls = trim(`"`controls'"')
    local absorb = trim(`"`absorb'"')
    local endo = trim(`"`endo'"')
    local inst = trim(`"`inst'"')
    local variant = lower(trim(`"`variant'"'))
    local se = lower(trim(`"`se'"'))
    local expr = trim(`"`expr'"')

    local sample
    if `"`ifcond'"' != "" local sample "if `ifcond'"
    local nativecmd

    if inlist(`"`action'"', "generate", "replace") {
        if `"`expr'"' == "" {
            display as error "请填写计算表达式。"
            exit 198
        }
        if `"`action'"' == "generate" {
            if `"`newvar'"' == "" {
                display as error "请填写新变量名。"
                exit 198
            }
            confirm new variable `newvar'
            local nativecmd "generate double `newvar' = `expr' `sample'"
        }
        else {
            if `"`target'"' == "" {
                display as error "请选择需要修改的变量。"
                exit 198
            }
            confirm variable `target'
            local nativecmd "replace `target' = `expr' `sample'"
        }
    }
    else if `"`action'"' == "summarize" {
        if `"`vars'"' == "" local vars "_all"
        local nativecmd "summarize `vars' `sample'"
        if `"`options'"' != "" local nativecmd "`nativecmd', `options'"
    }
    else if `"`action'"' == "tabstat" {
        if `"`vars'"' == "" {
            display as error "请选择至少一个变量。"
            exit 198
        }
        if `"`stats'"' == "" local stats "mean sd min p50 max n"
        local opts "statistics(`stats')"
        if `"`by'"' != "" local opts "`opts' by(`by')"
        if `"`options'"' != "" local opts "`opts' `options'"
        local nativecmd "tabstat `vars' `sample', `opts'"
    }
    else if `"`action'"' == "pwcorr" {
        if `"`vars'"' == "" {
            display as error "请选择至少两个变量。"
            exit 198
        }
        local opts = trim("sig obs `options'")
        local nativecmd "pwcorr `vars' `sample', `opts'"
    }
    else if `"`action'"' == "ttest" {
        gettoken one rest : vars
        if `"`one'"' == "" {
            display as error "请选择需要检验的变量。"
            exit 198
        }
        local nativecmd "ttest `one' `sample'"
        if `"`by'"' != "" local nativecmd "`nativecmd', by(`by') `options'"
        else if `"`value'"' != "" local nativecmd "ttest `one' == `value' `sample', `options'"
        else {
            display as error "请选择分组变量，或填写用于比较的数值。"
            exit 198
        }
    }
    else if `"`action'"' == "append" {
        if `"`usingfile'"' == "" {
            display as error "请选择需要追加的数据文件。"
            exit 198
        }
        confirm file `"`usingfile'"'
        local nativecmd `"append using "`usingfile'""'
        if `"`options'"' != "" local nativecmd `"`nativecmd', `options'"'
    }
    else if `"`action'"' == "reshape" {
        if !inlist(`"`direction'"', "long", "wide") | `"`stubs'"' == "" | `"`idvar'"' == "" | `"`jvar'"' == "" {
            display as error "宽长转换需要方向、变量前缀、个体标识 i() 和维度变量 j()。"
            exit 198
        }
        local nativecmd "reshape `direction' `stubs', i(`idvar') j(`jvar') `options'"
    }
    else if inlist(`"`action'"', "keepvars", "dropvars") {
        if `"`vars'"' == "" {
            display as error "请选择变量。"
            exit 198
        }
        local verb = substr(`"`action'"', 1, 4)
        local nativecmd "`verb' `vars'"
    }
    else if inlist(`"`action'"', "keepif", "dropif") {
        if `"`ifcond'"' == "" {
            display as error "请填写筛选条件。"
            exit 198
        }
        local verb = substr(`"`action'"', 1, 4)
        local nativecmd "`verb' if `ifcond'"
    }
    else if `"`action'"' == "duplicates" {
        if `"`vars'"' == "" {
            display as error "请选择用于判断重复记录的变量。"
            exit 198
        }
        if `"`variant'"' == "drop" local nativecmd "duplicates drop `vars', force"
        else local nativecmd "duplicates report `vars'"
    }
    else if `"`action'"' == "missing" {
        if `"`vars'"' == "" {
            display as error "请选择需要检查缺失值的变量。"
            exit 198
        }
        local missargs : subinstr local vars " " ",", all
        if `"`variant'"' == "drop" local nativecmd "drop if missing(`missargs')"
        else local nativecmd "misstable summarize `vars'"
    }
    else if inlist(`"`action'"', "regress", "xtreg", "reghdfe", "logit", "probit", "ivregress", "ppmlhdfe", "ivreghdfe") {
        if `"`y'"' == "" | `"`x'"' == "" {
            display as error "请选择被解释变量 Y 和至少一个核心 X。"
            exit 198
        }
        local rhs = trim(`"`x' `controls'"')
        local fe_rhs
        if `"`absorb'"' != "" & inlist(`"`action'"', "regress", "logit", "probit") {
            foreach f of local absorb {
                local fe_rhs "`fe_rhs' i.`f'"
            }
        }
        local vceopt
        if `"`se'"' == "robust" local vceopt "vce(robust)"
        if `"`se'"' == "cluster" {
            if `"`cluster'"' == "" {
                display as error "聚类标准误需要选择聚类变量。"
                exit 198
            }
            local vceopt "vce(cluster `cluster')"
        }
        local optlist = trim(`"`vceopt' `options'"')

        if inlist(`"`action'"', "regress", "logit", "probit") {
            local nativecmd "`action' `y' `rhs' `fe_rhs' `sample'"
        }
        else if `"`action'"' == "xtreg" {
            if !inlist(`"`variant'"', "fe", "re", "be") local variant "fe"
            local optlist = trim(`"`variant' `optlist'"')
            local nativecmd "xtreg `y' `rhs' `sample'"
        }
        else if inlist(`"`action'"', "reghdfe", "ppmlhdfe") {
            if `"`absorb'"' == "" {
                display as error "该方法需要至少一个固定效应变量。"
                exit 198
            }
            local optlist = trim(`"absorb(`absorb') `optlist'"')
            local nativecmd "`action' `y' `rhs' `sample'"
        }
        else if `"`action'"' == "ivregress" {
            if `"`endo'"' == "" | `"`inst'"' == "" {
                display as error "工具变量回归需要填写内生变量和工具变量。"
                exit 198
            }
            if !inlist(`"`variant'"', "2sls", "liml", "gmm") local variant "2sls"
            local nativecmd "ivregress `variant' `y' `rhs' (`endo' = `inst') `sample'"
        }
        else if `"`action'"' == "ivreghdfe" {
            if `"`endo'"' == "" | `"`inst'"' == "" | `"`absorb'"' == "" {
                display as error "ivreghdfe 需要内生变量、工具变量和固定效应。"
                exit 198
            }
            local optlist = trim(`"absorb(`absorb') `optlist'"')
            local nativecmd "ivreghdfe `y' `rhs' (`endo' = `inst') `sample'"
        }
        if `"`optlist'"' != "" local nativecmd "`nativecmd', `optlist'"
    }
    else if inlist(`"`action'"', "lincom", "test", "margins") {
        if `"`expr'"' == "" & `"`action'"' != "margins" {
            display as error "请填写需要计算或检验的表达式。"
            exit 198
        }
        local nativecmd "`action' `expr'"
        if `"`options'"' != "" local nativecmd "`nativecmd', `options'"
    }
    else {
        display as error "工具箱暂不支持操作：`action'"
        exit 198
    }

    local nativecmd = trim(itrim(`"`nativecmd'"'))
    capture window push `nativecmd'
    capture noisily `nativecmd'
    local rc = _rc
    capture hxregistry, recent(`action')
    capture hxhistory, add(`"`nativecmd'"')
    capture quietly hxrefresh
    if `rc' exit `rc'

    return local command `"`nativecmd'"'
end
