from pathlib import Path
p = Path('src/main/java/com/hexie/stata/HxWorkbench.java')
s = p.read_text(encoding='utf-8')

old = '''         HxWorkbench.WorkbenchFrame.CommandGuide var2 = COMMAND_GUIDES.get(this.currentCommand);\n         var1.label = var2 == null ? this.currentCommand : var2.title;\n         if ("regress".equals(this.currentCommand) && this.regressWorkspaceActive) {'''
new = '''         HxWorkbench.WorkbenchFrame.CommandGuide var2 = COMMAND_GUIDES.get(this.currentCommand);\n         var1.label = var2 == null ? this.currentCommand : var2.title;\n         if (this.baselineTaskActive) {\n            var1.label = "基准回归 · " + this.currentCommand;\n            var1.depvar = selected(this.depvar);\n            var1.x = selected(this.regressX);\n            var1.controls = String.join(" ", this.regressControls.getSelectedValuesList());\n            var1.extraTerms = this.joinSpecialTerms("|");\n            var1.vce = selected(this.vce);\n            var1.cluster = selected(this.cluster);\n            var1.ifcond = this.ifCondition.getText().trim();\n            var1.incond = this.inCondition.getText().trim();\n            var1.options = this.regressAdvancedOptions.getText().trim();\n            var1.weightType = selected(this.regressWeightType);\n            var1.weightVar = selected(this.regressWeightVar);\n            var1.flags = "baseline=1;xtmodel=" + selected(this.baselineXtModel) + ";absorb=" + String.join(",", this.absorb.getSelectedValuesList())\n               + ";" + (this.regressNoConstant.isSelected() ? "noconstant;" : "")\n               + (this.regressBeta.isSelected() ? "beta;" : "") + "level=" + this.regressLevel.getValue();\n         } else if ("regress".equals(this.currentCommand) && this.regressWorkspaceActive) {'''
if old not in s: raise SystemExit('missing capture anchor')
s = s.replace(old, new, 1)

old = '''         if (var1 != null && !var1.command.isBlank()) {\n            if ("regress".equals(var1.command)) {\n               this.openRegressWorkspace();'''
new = '''         if (var1 != null && !var1.command.isBlank()) {\n            if ("基准回归".equals(var1.method) || var1.flags.contains("baseline=1")) {\n               this.openBaselineRegressionWorkspace();\n               this.rebuilding = true;\n               this.setComboValue(this.baselineEstimator, var1.command);\n               this.setComboValue(this.depvar, var1.depvar);\n               this.setComboValue(this.regressX, var1.x);\n               setListSelectedValues(this.regressControls, splitWords(var1.controls));\n               this.regressSpecialTermsModel.clear();\n               for (String term : splitPipeTerms(var1.extraTerms)) this.regressSpecialTermsModel.addElement(term);\n               this.setComboValue(this.vce, var1.vce);\n               this.setComboValue(this.cluster, var1.cluster);\n               this.ifCondition.setText(var1.ifcond);\n               this.inCondition.setText(var1.incond);\n               this.setComboValue(this.regressWeightType, var1.weightType);\n               this.setComboValue(this.regressWeightVar, var1.weightVar);\n               this.regressAdvancedOptions.setText(var1.options);\n               Matcher xtMatcher = Pattern.compile("xtmodel=([^;]+)").matcher(var1.flags);\n               if (xtMatcher.find()) this.setComboValue(this.baselineXtModel, xtMatcher.group(1));\n               Matcher absorbMatcher = Pattern.compile("absorb=([^;]*)").matcher(var1.flags);\n               if (absorbMatcher.find() && !absorbMatcher.group(1).isBlank()) {\n                  setListSelectedValues(this.absorb, Arrays.asList(absorbMatcher.group(1).split(",")));\n               }\n               this.regressNoConstant.setSelected(var1.flags.contains("noconstant"));\n               this.regressBeta.setSelected(var1.flags.contains("beta"));\n               Matcher levelMatcher = Pattern.compile("level=([0-9]+)").matcher(var1.flags);\n               if (levelMatcher.find()) this.regressLevel.setValue(Integer.parseInt(levelMatcher.group(1)));\n               this.rebuilding = false;\n               this.switchBaselineEstimator();\n            } else if ("regress".equals(var1.command)) {\n               this.showCommand("regress");'''
if old not in s: raise SystemExit('missing restore anchor')
s = s.replace(old, new, 1)

# Regression diagnostics must still open the actual regress workspace, not baseline default xtreg.
s = s.replace('''                  this.openRegressWorkspace();\n                  this.selectResultView("regresspost", true);\n                  this.statusLabel.setText("这些诊断属于普通线性回归的后估计工具；请先运行 regress，再点击右侧诊断。");''', '''                  this.showCommand("regress");\n                  this.selectResultView("regresspost", true);\n                  this.statusLabel.setText("这些诊断属于普通线性回归的后估计工具；请先运行 regress，再点击右侧诊断。");''', 1)

p.write_text(s, encoding='utf-8')
print('HX_TASK_110_HOTFIX_OK')
